Repository Priyanshi662/FunFusion, pull requests merged in 2024-02, with the labels that each got.

#225 chess game added
  Assets/games/chess_2023-main/.vscode/launch.json
  Assets/games/chess_2023-main/Assets/Screenshot (90).png
  Assets/games/chess_2023-main/Assets/images/pieces/black/bishop.png
  Assets/games/chess_2023-main/Assets/images/pieces/black/king.png
  Assets/games/chess_2023-main/Assets/images/pieces/black/knight.png
  Assets/games/chess_2023-main/Assets/images/pieces/black/pawn.png
  Assets/games/chess_2023-main/Assets/images/pieces/black/queen.png
  Assets/games/chess_2023-main/Assets/images/pieces/black/rook.png
  Assets/games/chess_2023-main/Assets/images/pieces/white/bishop.png
  Assets/games/chess_2023-main/Assets/images/pieces/white/king.png
  Assets/games/chess_2023-main/Assets/images/pieces/white/knight.png
  Assets/games/chess_2023-main/Assets/images/pieces/white/pawn.png
  Assets/games/chess_2023-main/Assets/images/pieces/white/queen.png
  Assets/games/chess_2023-main/Assets/images/pieces/white/rook.png
  Assets/games/chess_2023-main/Data/data.js
  Assets/games/chess_2023-main/Data/data.json
  Assets/games/chess_2023-main/Data/pieces.js
  Assets/games/chess_2023-main/Events/global.js
  Assets/games/chess_2023-main/Helper/commonHelper.js
  Assets/games/chess_2023-main/Helper/constants.js
  Assets/games/chess_2023-main/Helper/modalCreator.js
  Assets/games/chess_2023-main/README.md
  Assets/games/chess_2023-main/Render/main.js
  Assets/games/chess_2023-main/index.html
  Assets/games/chess_2023-main/index.js
  Assets/games/chess_2023-main/styles/index.css
  index.html
Labels: JWOC, Hard

#243 added cosmoXplore
  images/Screenshot (91).png
  index.html
Labels: JWOC, Hard

#246 Added BMI calculator
  Bmi/Screenshot (75).png
  Bmi/index.html
  Bmi/script.js
  Bmi/styles.css
  index.html
Labels: JWOC, medium

#247 Add Gradient Color Generator #237
  color/img.png
  color/index.html
  color/script.js
  color/style.css
  index.html
Labels: JWOC, Hard

#252 MINOR BUG IS FIXED
  Assets/games/Snake_Ladder/game.js
Labels: JWOC, medium

#253 [ISSUE - 233] Adding of a Checkers Game
  Assets/games/Checkers Game/index.html
  Assets/games/Checkers Game/logo.png
  Assets/games/Checkers Game/script.js
  Assets/games/Checkers Game/style.css
  index.html
Labels: JWOC, Hard

#255 add weather app
  images/Screenshot 2024-02-02 175253.png
  index.html
Labels: JWOC, Hard

#256 All cards are updated
  index.html
Labels: JWOC, medium

#266 enhanced rate us page look
  rate/emojis/Screenshot from 2024-02-03 15-17-44.png
  rate/index.html
  rate/style.css
Labels: JWOC, medium

#265 FEAT add Ping pong game completed #232
  Assets/games/ping pong game/Ping-Pong.js
  Assets/games/ping pong game/Ping-pong.html
  Assets/games/ping pong game/ping pong image.png
  index.html
Labels: JWOC, Hard

#236 press the key game (resolved)
  index.html
  keyCode/keyCode.css
  keyCode/keyCode.html
  keyCode/keyCode.js
  keyCode/logo-key.png
Labels: JWOC, Hard

#263 added reaction time game
  Assets/games/Reaction_Time/README.md
  Assets/games/Reaction_Time/banner.jpg
  Assets/games/Reaction_Time/index.html
  Assets/games/Reaction_Time/script.js
  Assets/games/Reaction_Time/style.css
  index.html
Labels: JWOC, Hard

#271 Added Recipe App using API
  Recipe-App/Screenshot (85).png
  Recipe-App/index.html
  Recipe-App/script.js
  Recipe-App/style.css
  index.html
Labels: JWOC, Hard

#272 created feedback page
  feed.css
  feed.html
  index.html
  thank.html
Labels: enhancement, JWOC, Hard

#274 [Enhancement] Improve UI for contributor button
  Assets/css/style.css
  index.html
Labels: JWOC, Easy

#275 Feat: Add a dictionary application Issue #269
  dictionary/img.png
  dictionary/index.html
  dictionary/script.js
  dictionary/style.css
  index.html
Labels: JWOC, medium

#277 rubiks-cube-added
  Assets/games/Rubiks-cube/image.png
  Assets/games/Rubiks-cube/index.html
  Assets/games/Rubiks-cube/script.js
  Assets/games/Rubiks-cube/style.css
  index.html
Labels: JWOC, Hard

#284 FEAT add new Avoider Game #264
  Assets/games/Avoider-Game/README.md
  Assets/games/Avoider-Game/app.js
  Assets/games/Avoider-Game/assets/AV.png
  Assets/games/Avoider-Game/assets/bgMusic.mp3
  Assets/games/Avoider-Game/assets/boy.png
  Assets/games/Avoider-Game/assets/demon.png
  Assets/games/Avoider-Game/assets/gameOver.wav
  Assets/games/Avoider-Game/assets/move.mp3
  Assets/games/Avoider-Game/index.html
  Assets/games/Avoider-Game/style.css
  index.html
Labels: JWOC, Hard

#286 contact us section
  images/pngaaa.com-4606018.png
  index.html
Labels: JWOC, medium

#289 Added Home button
  Assets/css/style.css
  index.html
Labels: JWOC, medium

#290 added rubiks game #288
  Assets/games/Rubiks_Game/README.md
  Assets/games/Rubiks_Game/index.html
  Assets/games/Rubiks_Game/logo.png
  Assets/games/Rubiks_Game/script.js
  Assets/games/Rubiks_Game/style.css
  index.html
Labels: JWOC, Hard

#292 ghost-game-added
  Assets/games/Ghost Game/image.png
  Assets/games/Ghost Game/index.html
  Assets/games/Ghost Game/script.js
  Assets/games/Ghost Game/style.css
  index.html
Labels: JWOC, Hard

#296 added hover to the contributor part
  contributor.css
Labels: JWOC, Easy

#298 FEAT: add login/signup page #276
  index.html
  login/Images/backImg.jpg
  login/Images/frontImg.jpg
  login/index.html
  login/style.css
Labels: JWOC, Hard

#300 added-candy-crush
  Assets/games/Candy-Crush/board.js
  Assets/games/Candy-Crush/candy.js
  Assets/games/Candy-Crush/graphics/Thumbs.db
  Assets/games/Candy-Crush/graphics/blue-candy.png
  Assets/games/Candy-Crush/graphics/blue-special.png
  Assets/games/Candy-Crush/graphics/color-bomb.png
  Assets/games/Candy-Crush/graphics/green-candy.png
  Assets/games/Candy-Crush/graphics/green-special.png
  Assets/games/Candy-Crush/graphics/orange-candy.png
  Assets/games/Candy-Crush/graphics/orange-special.png
  Assets/games/Candy-Crush/graphics/purple-candy.png
  Assets/games/Candy-Crush/graphics/purple-special.png
  Assets/games/Candy-Crush/graphics/red-candy.png
  Assets/games/Candy-Crush/graphics/red-special.png
  Assets/games/Candy-Crush/graphics/yellow-candy.png
  Assets/games/Candy-Crush/handler.js
  Assets/games/Candy-Crush/images.jpg
  Assets/games/Candy-Crush/index.html
  Assets/games/Candy-Crush/mainLayout.css
  Assets/games/Candy-Crush/rules.js
  index.html
Labels: JWOC, Hard

#294 [ISSUE - 262] Adding a FAQ Page for the website
  Assets/css/style.css
  faq/faq.css
  faq/faq.html
  faq/faq.js
  index.html
Labels: JWOC, Hard

#305 effect on wordsscramblegame
  wordscramble/js/script.js
  wordscramble/style.css
Labels: JWOC, Easy

#302 Created a navbar
  Assets/css/style.css
  index.html
Labels: JWOC, medium

#307 Added Magic Tiles Game
  Assets/games/Magic-Tiles/images.jpg
  Assets/games/Magic-Tiles/index.html
  Assets/games/Magic-Tiles/script.js
  Assets/games/Magic-Tiles/style.css
  index.html
Labels: JWOC, Hard

#310 added hover effect to the button
  Riddles/index.html
  Riddles/style.css
  Snake Game/snakegame.html
Labels: JWOC, medium

#311 Add new race car game #291
  Assets/games/race_car/README.md
  Assets/games/race_car/images/1icon.png
  Assets/games/race_car/images/car.png
  Assets/games/race_car/images/car04.png
  Assets/games/race_car/images/cloud.jpg
  Assets/games/race_car/images/finish.png
  Assets/games/race_car/images/hero.png
  Assets/games/race_car/images/icon.png
  Assets/games/race_car/images/tree.png
  Assets/games/race_car/index.html
  Assets/games/race_car/script.js
  Assets/games/race_car/style.css
  index.html
Labels: JWOC, Hard

#315 Dark & Light Mode added
  Assets/css/image.png
  Assets/css/style.css
  index.html
Labels: JWOC, medium

#319 FEAT: Add pig (dice game) #301
  index.html
  piggame/images/dice-1.png
  piggame/images/dice-2.png
  piggame/images/dice-3.png
  piggame/images/dice-4.png
  piggame/images/dice-5.png
  piggame/images/dice-6.png
  piggame/index.html
  piggame/script.js
  piggame/style.css
Labels: JWOC, Hard

#322 Created a customised scrollbar
  Assets/css/style.css
Labels: JWOC, medium

#323 jisaw-puzzle-added
  Assets/games/Jigsaw Puzzle/image.png
  Assets/games/Jigsaw Puzzle/index.html
  Assets/games/Jigsaw Puzzle/script.js
  Assets/games/Jigsaw Puzzle/style.css
  index.html
Labels: JWOC, Hard

#327 Added Joke Generator
  Joke Generator/Image.png
  Joke Generator/index.html
  Joke Generator/script.js
  Joke Generator/style.css
  index.html
Labels: JWOC, Hard

#329 FIX cookie consent box #320
  index.html
Labels: JWOC, Easy

#331 #324 Fixed the issues
  index.html
Labels: JWOC, medium

#335 fixed messed up code and footer
  index.html
Labels: JWOC, Easy

#342 Added Random Name Generator
  Random Name Generator/Screenshot 2024-02-13 004217.png
  Random Name Generator/function.js
  Random Name Generator/index.html
  Random Name Generator/styles.css
  index.html
Labels: JWOC, medium

#344 Modified the faq page
  faq/faq.css
  faq/faq.html
  index.html
Labels: JWOC, medium

#348 Fixed and modified Canvas issue #259
  Assets/games/Canvas/Mycanvas.html
  Assets/games/Canvas/icons/brush.svg
  Assets/games/Canvas/icons/circle.svg
  Assets/games/Canvas/icons/eraser.svg
  Assets/games/Canvas/icons/rectangle.svg
  Assets/games/Canvas/icons/triangle.svg
  Assets/games/Canvas/script.js
  Assets/games/Canvas/style.css
Labels: JWOC, Hard

#336 stick hero game
  Assets/games/STICK HERO/hero.css
  Assets/games/STICK HERO/index.html
  Assets/games/STICK HERO/logic.js
  Assets/games/STICK HERO/ss_stick_hero.png
  index.html
Labels: JWOC, Hard

#347 Added a random color generator as a contribution under JWOC'24
  Color Generator/RandomColorLogo.png
  Color Generator/app.js
  Color Generator/index.html
  Color Generator/style.css
  index.html
Labels: JWOC, medium

#357 Added Customized Emoji Generator !
  Customized Emoji Generator/Emoji-Maker.png
  Customized Emoji Generator/eye-0.svg
  Customized Emoji Generator/eye-1.svg
  Customized Emoji Generator/eye-2.svg
  Customized Emoji Generator/eye-3.svg
  Customized Emoji Generator/eye-4.svg
  Customized Emoji Generator/eyebrow-0.svg
  Customized Emoji Generator/eyebrow-1.svg
  Customized Emoji Generator/eyebrow-2.svg
  Customized Emoji Generator/eyebrow-3.svg
  Customized Emoji Generator/index.html
  Customized Emoji Generator/mouth-0.svg
  Customized Emoji Generator/mouth-1.svg
  Customized Emoji Generator/mouth-2.svg
  Customized Emoji Generator/mouth-3.svg
  Customized Emoji Generator/mouth-4.svg
  Customized Emoji Generator/script.js
  Customized Emoji Generator/style.css
  index.html
Labels: JWOC, Hard

#358 Created a contact page
  contact.css
  contact.html
  index.html
Labels: JWOC, medium

#360 modified-go-to-top
  Assets/css/style.css
  index.html
Labels: JWOC, medium

#361 Added a Resize and Compress Images Application
  img/img.jpg
  img/img1.png
  img/index.html
  img/script.js
  img/style.css
  img/upload-icon.svg
  index.html
Labels: JWOC, Hard

#364 Improve Sudoku Game
  Assets/games/Checkers Game/style.css
  Assets/games/Sudoku/index.html
  Assets/games/Sudoku/script.js
  Assets/games/Sudoku/style.css
Labels: JWOC, medium

#366 Fixed the bugs
  index.html
Labels: JWOC, medium

#370 Added 8 Puzzle Game
  Assets/games/8 Puzzle/_8_Puzzle.png
  Assets/games/8 Puzzle/_8_Puzzle_game.css
  Assets/games/8 Puzzle/_8_Puzzle_game.html
  Assets/games/8 Puzzle/_8_Puzzle_game.js
  index.html
Labels: JWOC, Hard

#375 Added Crossword Game
  Assets/games/CrossWord/app.js
  Assets/games/CrossWord/crossword.png
  Assets/games/CrossWord/index.html
  Assets/games/CrossWord/style.css
  index.html
Labels: JWOC, Hard

#376 add new game Word-Scramble #374
  Assets/games/Word-Scramble/Word-Scramble.png
  Assets/games/Word-Scramble/index.html
  Assets/games/Word-Scramble/script.js
  Assets/games/Word-Scramble/style.css
  Assets/games/Word-Scramble/words.js
  index.html
Labels: JWOC, Hard

#377 Done the changes in faq page
  faq/faq.css
  faq/faq.html
  faq/scroll.js
Labels: JWOC, medium

#384 Added navbar and footer to the contributor page
  contributor.css
  contributor.html
Labels: JWOC, medium

#386 Style Improve snake game #383
  Snake Game/index.html
  Snake Game/script.css
  Snake Game/script.js
  Snake Game/snakegame.html
  Snake Game/style.css
  index.html
Labels: JWOC, Hard

#389 Improved the rate us page
  rate/index.html
  rate/style.css
Labels: JWOC, medium

#392 Improved Random Colour Generator
  Color Generator/RandomColorLogo.png
  Color Generator/Random_Color_Generator.png
  Color Generator/app.js
  Color Generator/index.html
  Color Generator/script.js
  Color Generator/style.css
  index.html
Labels: JWOC, Hard

#393 Added Sorting Visualizer
  Assets/games/sort-visualizer/css/style.css
  Assets/games/sort-visualizer/index.html
  Assets/games/sort-visualizer/scripts/app.js
  Assets/games/sort-visualizer/scripts/helper.js
  Assets/games/sort-visualizer/scripts/sort-algorithms.js
  Assets/games/sort-visualizer/sort-visualizer.png
  index.html
Labels: JWOC, Hard

#395 add new joke telling game #388
  Assets/games/Joke-Telling-Website/Joke-Telling-Website.webp
  Assets/games/Joke-Telling-Website/index.html
  Assets/games/Joke-Telling-Website/script.js
  Assets/games/Joke-Telling-Website/style.css
  index.html
Labels: JWOC, Hard

#397 added-bubble-shooter
  Assets/games/Bubble-Shooter/image.PNG
  Assets/games/Bubble-Shooter/index.html
  Assets/games/Bubble-Shooter/script.js
  Assets/games/Bubble-Shooter/style.css
  index.html
Labels: JWOC, Hard

#398 Added Rock Paper Scissor
  Rock Paper Scissor/images/cover.png
  Rock Paper Scissor/images/paper.png
  Rock Paper Scissor/images/rock.png
  Rock Paper Scissor/images/scissor.png
  Rock Paper Scissor/index.html
  Rock Paper Scissor/script.js
  Rock Paper Scissor/style.css
  index.html
Labels: JWOC, Hard

#399 Added customised scrollbar to all the pages
  contact.css
  contributor.css
  rate/style.css
Labels: JWOC, medium

#402 Add new interval time #390
  Assets/games/Interval-Time/Interval.png
  Assets/games/Interval-Time/css/style.min.css
  Assets/games/Interval-Time/index.html
  Assets/games/Interval-Time/js/main.js
  Assets/games/Interval-Time/js/main.min.js
  Assets/games/Interval-Time/scss/_app.scss
  Assets/games/Interval-Time/scss/_buttons.scss
  Assets/games/Interval-Time/scss/_header.scss
  Assets/games/Interval-Time/scss/_media.scss
  Assets/games/Interval-Time/scss/_ready.scss
  Assets/games/Interval-Time/scss/_reset.scss
  Assets/games/Interval-Time/scss/_vars.scss
  Assets/games/Interval-Time/scss/style.scss
  Assets/games/Interval-Time/sounds/finish.mp3
  Assets/games/Interval-Time/sounds/pick.mp3
  Assets/games/Interval-Time/sounds/start.mp3
  index.html
Labels: JWOC, Hard

#405 Improve the login page
  login/index.html
  login/style.css
Labels: JWOC, medium

#407 Add new game Quote-Generator- #404
  Assets/games/Quote/Quote.png
  Assets/games/Quote/README.md
  Assets/games/Quote/favicon.png
  Assets/games/Quote/index.html
  Assets/games/Quote/script.js
  Assets/games/Quote/style.css
  index.html
Labels: JWOC, Hard

#412 Battery status tracker added
  Assets/games/Battery-Status-Tracker/Battery-Status-Tracker.webp
  Assets/games/Battery-Status-Tracker/assets/img/favicon.png
  Assets/games/Battery-Status-Tracker/index.html
  Assets/games/Battery-Status-Tracker/main.js
  Assets/games/Battery-Status-Tracker/styles.css
  index.html
Labels: JWOC, medium

#416 Added StopWatch !
  STOPWATCH/Image.png
  STOPWATCH/index.html
  STOPWATCH/reset.png
  STOPWATCH/script.js
  STOPWATCH/style.css
  index.html
Labels: JWOC, Hard

#417 Add Mars Imagery feature
  Mars-Imagery/Screenshot 2024-02-24 161201.png
  Mars-Imagery/index.html
  index.html
Labels: JWOC, Hard

#418 Added alarm clock
  alarmclock/clock.svg
  alarmclock/index.html
  alarmclock/ringtone.mp3
  alarmclock/script.js
  alarmclock/style.css
  index.html
Labels: JWOC, Hard

#422 Ball_Slider Game added.
  Assets/games/Ball_Slider/ball_pic.png
  Assets/games/Ball_Slider/index.html
  Assets/games/Ball_Slider/main.js
  Assets/games/Ball_Slider/style.css
  index.html
Labels: JWOC, Hard

#424 add new ball game #408
  Assets/games/Throw-Ball/ball game.png
  Assets/games/Throw-Ball/images/assets.fla
  Assets/games/Throw-Ball/images/lv1.png
  Assets/games/Throw-Ball/images/lv2.png
  Assets/games/Throw-Ball/images/lv3.png
  Assets/games/Throw-Ball/images/lv4.png
  Assets/games/Throw-Ball/images/lv5.jpg
  Assets/games/Throw-Ball/images/lv6.jpg
  Assets/games/Throw-Ball/index.html
  Assets/games/Throw-Ball/scripts/assets.js
  Assets/games/Throw-Ball/scripts/game.js
  Assets/games/Throw-Ball/scripts/helpers.js
  Assets/games/Throw-Ball/scripts/level.js
  Assets/games/Throw-Ball/scripts/physics.js
  Assets/games/Throw-Ball/scripts/view.js
  Assets/games/Throw-Ball/styles/game.css
  Assets/games/Throw-Ball/vendors/Box2dWeb-2.1.a.3.min.js
  Assets/games/Throw-Ball/vendors/easeljs-0.7.1.min.js
  Assets/games/Throw-Ball/vendors/movieclip-0.7.1.min.js
  Assets/games/Throw-Ball/vendors/preloadjs-0.4.1.min.js
  Assets/games/Throw-Ball/vendors/tweenjs-0.5.1.min.js
  Assets/games/To-do list/ball game.png
  index.html
Labels: JWOC, Hard

#420 smallerscreen heading fixed
  Assets/css/style.css
  index.html
Labels: JWOC, medium

#426 Add new game unitangle #423
  Assets/games/Untangle/NewUn.png
  Assets/games/Untangle/css/untangle.css
  Assets/games/Untangle/images/bg.webp
  Assets/games/Untangle/images/bg_repeat.png
  Assets/games/Untangle/images/guide_sprite.png
  Assets/games/Untangle/index.html
  Assets/games/Untangle/js/jquery-2.1.3.min.js
  Assets/games/Untangle/js/untangle.data.js
  Assets/games/Untangle/js/untangle.drawing.js
  Assets/games/Untangle/js/untangle.game.js
  Assets/games/Untangle/js/untangle.input.js
  Assets/games/Untangle/js/untangle.js
  Assets/games/Untangle/js/untangle.levels.js
  Assets/games/Untangle/readme.md
  index.html
Labels: JWOC, Hard

#430 Added Morse Code Encoder Decoder
  Assets/games/Morse Code Convertor/Morse.png
  Assets/games/Morse Code Convertor/index.html
  Assets/games/Morse Code Convertor/script.js
  Assets/games/Morse Code Convertor/styles.css
  index.html
Labels: JWOC, Hard

#433 add nasa media gallery
  NasaMedia/Screenshot 2024-02-23 231514.png
  NasaMedia/index.html
  index.html
Labels: JWOC, Hard

#434 Added a QR code Generator
  QRcode/index.html
  QRcode/style.css
  index.html
Labels: JWOC, Hard

#436 Added Image Background Remover
  Assets/games/background-remover/app.js
  Assets/games/background-remover/background-remover.png
  Assets/games/background-remover/index.html
  Assets/games/background-remover/style.css
  index.html
Labels: JWOC, Hard
