Repository Priyanshi662/FunFusion, pull requests merged in 2024-01, with the labels that each got.

#30 Added Typing Speed Test Game
  Typing Speed Test/TypingSpeedTest.jpg
  Typing Speed Test/index.html
  Typing Speed Test/js/paragraphs.js
  Typing Speed Test/js/script.js
  Typing Speed Test/style.css
  index.html
Labels: JWOC, Hard

#31 added logo
  Canvas/Mycanvas.html
Labels: JWOC, Easy

#33 Added button hover effects and aligned game cards
  index.html
Labels: JWOC, Easy

#35 Add memory card game #19
  Memory Game/images/icon.jpeg
  Memory Game/images/img-1.png
  Memory Game/images/img-2.png
  Memory Game/images/img-3.png
  Memory Game/images/img-4.png
  Memory Game/images/img-5.png
  Memory Game/images/img-6.png
  Memory Game/images/img-7.png
  Memory Game/images/img-8.png
  Memory Game/images/img.png
  Memory Game/index.html
  Memory Game/script.js
  Memory Game/style.css
  index.html
Labels: JWOC, Hard

#58 Update README.md file #48
  README.md
Labels: documentation, JWOC, Easy

#71 [FEA]: Archery game added
  Archery/index.html
  Archery/logo.jpg
  Archery/script.js
  Archery/styles.css
  index.html
Labels: JWOC, Hard

#73 Added the Super Hero app
  SuperHero/.cache/replit/__replit_disk_meta.json
  SuperHero/.cache/replit/modules.stamp
  SuperHero/.cache/replit/nix/env.json
  SuperHero/.config/configstore/update-notifier-npm.json
  SuperHero/.config/configstore/update-notifier-npm.json.2701252402
  SuperHero/.replit
  SuperHero/images/Cover.jpg
  SuperHero/index.html
  SuperHero/replit.nix
  SuperHero/script.js
  SuperHero/style.css
  index.html
Labels: JWOC, medium

#126 Created a footer
  Assets/css/style.css
  index.html
Labels: enhancement, JWOC, Hard

#127 [added] search bar on home page #63
  css/style.css
  images/search.png
  index.html
Labels: JWOC, medium

#129 [ISSUE - 109] Minesweeper Game Addition
  Assets/games/Minesweeper/index.html
  Assets/games/Minesweeper/minesweeper.png
  Assets/games/Minesweeper/script.js
  Assets/games/Minesweeper/style.css
  index.html
Labels: JWOC, Hard

#113 added no guess game
  Assets/games/guess_the_no/Screenshot 2024-01-22 171515.png
  Assets/games/guess_the_no/app.js
  Assets/games/guess_the_no/index.html
  Assets/games/guess_the_no/style.css
  index.html
Labels: JWOC, Hard

#125 Added Highway Racing
  Assets/games/Highway-Race/image.jpg
  Assets/games/Highway-Race/index.html
  Assets/games/Highway-Race/script.js
  Assets/games/Highway-Race/style.css
  index.html
Labels: JWOC, Hard

#137 added/wordle_game
  Assets/games/Wordle Game/index.html
  Assets/games/Wordle Game/script.js
  Assets/games/Wordle Game/style.css
  Assets/games/Wordle Game/word.json
  Assets/games/Wordle Game/wordle.png
  index.html
Labels: JWOC, Hard

#122 Add color blast game
  Assets/games/Color blast/index.html
  Assets/games/Color blast/rain.jpg
  Assets/games/Color blast/script.js
  Assets/games/Color blast/style.css
  Assets/games/Tower Blocks/index.html
  Assets/games/Tower Blocks/style.css
  index.html
Labels: JWOC, Hard

#146 [ISSUE - 132] Flappy Bird Game Addition
  Assets/games/Flappy Bird/assets/fBird.png
  Assets/games/Flappy Bird/assets/flappy-bird-set.png
  Assets/games/Flappy Bird/index.html
  Assets/games/Flappy Bird/script.js
  Assets/games/Flappy Bird/style.css
  index.html
Labels: JWOC, Hard

#147 FEAT: Add an AI image generator #101
  ai/ai.png
  ai/index.html
  ai/syte.css
  index.html
Labels: JWOC, Hard

#153 Feat: Adding Word Scramble Game #138
  index.html
  wordscramble/img.png
  wordscramble/index.html
  wordscramble/js/script.js
  wordscramble/js/words.js
  wordscramble/style.css
Labels: JWOC, Hard

#149 fix #47 added block buster
  Assets/games/Block_Buster/README.md
  Assets/games/Block_Buster/banner.png
  Assets/games/Block_Buster/index.html
  Assets/games/Block_Buster/script.js
  Assets/games/Block_Buster/styles.css
  index.html
Labels: JWOC, Hard

#167 added icon
  images/funfusion-logo.png
  index.html
Labels: JWOC, Easy

#169 Add: Bubble Game
  Bubble-Game/Bubble Game.png
  Bubble-Game/README.md
  Bubble-Game/index.html
  Bubble-Game/script.js
  Bubble-Game/style.css
  index.html
Labels: JWOC, Hard

#181 Added Coin Toss Game
  Coin Toss Game/index.html
  Coin Toss Game/script.js
  Coin Toss Game/style.css
Labels: JWOC, Hard

#186 Added English Dictionary
  English Dictionary/index.html
  English Dictionary/script.js
  English Dictionary/styles.css
Labels: JWOC, Hard

#194 Shooting-bird-game
  Assets/bird shooting/bird.jpg
  Assets/bird shooting/index.html
  Assets/bird shooting/style.css
  index.html
Labels: JWOC, medium

#200 [ISSUE - 193] Addition of a Carrom Board Game
  Assets/games/Carrom Board Game/carrom.png
  Assets/games/Carrom Board Game/css/bootstrap.min.css
  Assets/games/Carrom Board Game/css/main.css
  Assets/games/Carrom Board Game/index.html
  Assets/games/Carrom Board Game/js/bootstrap.min.js
  Assets/games/Carrom Board Game/js/canvasCalls.js
  Assets/games/Carrom Board Game/js/canvasFunc.js
  Assets/games/Carrom Board Game/js/coinFunc.js
  Assets/games/Carrom Board Game/js/jquery.js
  Assets/games/Carrom Board Game/js/main.js
  index.html
Labels: JWOC, Hard

#201 added-TilingMaze Game Fixes #173
  Assets/games/TilingMazeGame/OIP.jpg
  Assets/games/TilingMazeGame/index.html
  Assets/games/TilingMazeGame/script.js
  Assets/games/TilingMazeGame/style.css
  Assets/games/TilingMazeGame/tilingmaze.png
  index.html
Labels: JWOC, Hard

#203 fix footer
  index.html
Labels: JWOC, medium

#221 tetris-game-added
  Assets/games/Tetris/Tetris.PNG
  Assets/games/Tetris/index.html
  index.html
Labels: JWOC, Hard

#231 Adding random quote generator #183
  index.html
  quote/img.png
  quote/index.html
  quote/script.js
  quote/style.css
Labels: JWOC, medium
